#!/bin/sh

cd pimpleCentral; wclean; wcleanLnIncludeAll; cd ../

cd pimpleHLLCFoam; ./Allwclean; cd ../

cd reactingPimpleCentralFoam; ./Allwclean; cd ../

cd twoPhaseMixingCentralFoam; ./Allwclean; cd ../

cd chtMultiRegionCentralFoam; ./Allwclean; cd ../

#
#END-OF-FILE
#

