#!/bin/sh

cd pimpleCentral; wmake libso; cd ../

cd pimpleHLLCFoam; ./Allwmake; cd ../

cd reactingPimpleCentralFoam; ./Allwmake; cd ../

cd twoPhaseMixingCentralFoam; ./Allwmake; cd ../

cd chtMultiRegionCentralFoam; ./Allwmake; cd ../

#
#END-OF-FILE
#


